leftnav:
- identifier: 5dfa4d63-522e-4c10-bf4e-caf1f232a644
  name: a page
  pageRef: /pages/page
  weight: 10
- identifier: 860ad17e-9424-4178-bf2f-d908b5eb05cb
  name: google.com
  pageRef: /external-resources/google
  weight: 20
- identifier: 0e2dbbb2-39de-4149-9b35-0dcb2cf4adee
  name: An image
  pageRef: /external-resources/an-image
  weight: 30
